### ISSUE TITLE
无法将“weapp_fc”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。需要全局配置吗

### ISSUE THREAD

**Issue by yang1-yang** [schizobulia/fc#3]

**Comment by schizobulia** [comment]
或者这样会对你有一些帮助[点击跳转](https://www.bing.com/search?q=%E6%97%A0%E6%B3%95%E5%B0%86%E2%80%9Cxxx%E2%80%9D%E9%A1%B9%E8%AF%86%E5%88%AB%E4%B8%BA+cmdlet%E3%80%81%E5%87%BD%E6%95%B0%E3%80%81%E8%84%9A%E6%9C%AC%E6%96%87%E4%BB%B6%E6%88%96%E5%8F%AF%E8%BF%90%E8%A1%8C%E7%A8%8B%E5%BA%8F%E7%9A%84%E5%90%8D%E7%A7%B0&qs=n&form=QBRE&sp=-1&pq=%E6%97%A0%E6%B3%95%E5%B0%86%E2%80%9Cx%27x%27x%E2%80%9D%E9%A1%B9%E8%AF%86%E5%88%AB%E4%B8%BA+cmdlet%E3%80%81%E5%87%BD%E6%95%B0%E3%80%81%E8%84%9A%E6%9C%AC%E6%96%87%E4%BB%B6%E6%88%96%E5%8F%AF%E8%BF%90%E8%A1%8C%E7%A8%8B%E5%BA%8F%E7%9A%84%E5%90%8D%E7%A7%B0&sc=1-38&sk=&cvid=C7FBA53B2BC0450F96BD664E4CB3277B&ghsh=0&ghacc=0&ghpl=)
